config/routes.rb
Rails.application.routes.draw do
  resources :boxes, :links

  root 'boxes#index'

end

app/models/box.rb
class Box < ActiveRecord::Base
end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  def index
    @boxes = Box.all
  end

  def new
    @box = Box.new
  end

  def create
    @box = Box.new(box_params)

    @box.save
    redirect_to @box
  end

  def show
    @box = Box.find(params[:id])
  end

  def edit
    @box = Box.find(params[:id])
  end

  def update
    @box = Box.find(params[:id])

    if @box.update(box_params)
      redirect_to @box
    else
      render 'edit'
    end
  end

  private
    def box_params
      params.require(:box).permit(:title1,
                                  :url1,
                                  :title2,
                                  :url2,
                                  :title3,
                                  :url3)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

def new
end

def create
  @link = Link.new(link_params)

  @link.save
  redirect_to links_path
end

def show
  @link = Link.find(params[:id])
end

def index
  @links = Link.all
end


private
  def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/box_helper.rb
module BoxHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/boxes/_form.html.erb
<%= form_for @box do |f| %>
  <p>
    <%= f.label 'Title 1' %><br>
    <%= f.text_field :title1 %>
  </p>

  <p>
    <%= f.label 'Url 1' %><br>
    <%= f.text_field :url1 %>
  </p>

  <p>
    <%= f.label 'Title 2' %><br>
    <%= f.text_field :title2 %>
  </p>

  <p>
    <%= f.label 'Url 2' %><br>
    <%= f.text_field :url2 %>
  </p>

  <p>
    <%= f.label 'Title 3' %><br>
    <%= f.text_field :title3 %>
  </p>

  <p>
    <%= f.label 'Url 3' %><br>
    <%= f.text_field :url3 %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/boxes/edit.html.erb
<h1>Edit Box</h1>

<%= render 'form' %>

<%= link_to 'Boxes', boxes_path %>

app/views/boxes/index.html.erb
<h1>Box Index</h1>

<% @boxes.each do |box| %>

<div class="box">
  <h2>
    <%= link_to 'Name of Person', box_path(box.id)%>
  </h2>
  <p>
    <%= link_to box.title1, box.url1%>
  </p>

  <p>
    <%= link_to box.title2, box.url2%>
  </p>

  <p>
    <%= link_to box.title3, box.url3%>
  </p>
</div>

<% end %>

<hr>
<p>
  <%= link_to 'new box', new_box_path %>
</p>

app/views/boxes/new.html.erb
<h1>New Box</h1>

<%= render 'form' %>

<%= link_to 'Boxes', boxes_path %>

app/views/boxes/show.html.erb
<div class="box">
  <h2>
    Name of Person
  </h2>
  <p>
    <%= link_to @box.title1, @box.url1%>
  </p>

  <p>
    <%= link_to @box.title2, @box.url2%>
  </p>

  <p>
    <%= link_to @box.title3, @box.url3%>
  </p>
</div>

<%= link_to 'Edit', edit_box_path(@box) %>
<%= link_to 'Boxes', boxes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/index.html.erb
<h1>Link Index</h1>

<div>
  <% @links.each do |link| %>
  <p>
    <%= link_to link.title, link.url%>
  </p>
  <% end %>
  <hr>
  <p>
    <%= link_to 'new link', new_link_path %>
  </p>
</div>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= form_for :link, url: links_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Links', links_path %>

app/views/links/show.html.erb
<p>
  <%= link_to @link.title, @link.url%>
</p>

<%= link_to 'Links', links_path %>